---
ID: "ea179340-670f-493f-b2b5-10f7d7180eeb"
Parent: "bbc556b4-5cc2-4db2-aa25-36acca5e7333"
Template: "bbc556b4-5cc2-4db2-aa25-36acca5e7333"
Path: /sitecore/templates/Conjunction/Foundation/ComparisonOperator/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161118T155910Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
