---
ID: "b0ca092b-7e41-4977-b634-99a01c645e9e"
Parent: "5c28b108-98f6-4840-ae14-f3633b2550ba"
Template: "5c28b108-98f6-4840-ae14-f3633b2550ba"
Path: /sitecore/templates/Conjunction/Foundation/LogicalOperator/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161118T182619Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
