---
ID: "bee28558-0a5d-4ee1-b54f-a9d25596a249"
Parent: "c1b93a34-44a6-41e9-a9f1-7cf30c38b9b6"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Conjunction/Foundation/_IndexableEntityConfigurator/IndexableEntityConfigurator/IndexableEntityConfiguratorConfiguredIndexableEntityType
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: "Single-Line Text"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Configured Indexable Entity Type
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161116T201857Z
